### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by retog** [AKSW/node_ldp#10]
Trying out node_ldp I'm failing at the very begining:

```
$ bin/start 

path.js:336
    var isAbsolute = path.charAt(0) === '/',
                          ^
TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at Object.exports.start (/tmp/node_ldp/lib/server.js:53:25)
    at Object.<anonymous> (/tmp/node_ldp/bin/start:30:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

I'm using ubuntu 14.04 with nodejs v0.10.25

**Comment by akuckartz** [comment]
See `README.md`: "Fake namespace and initial triples file are currently required."

**Comment by 0xfeedface** [comment]
Hi retog, your can start node_ldp using `bin/start -l test/empty.ttl` as a workaround.
