### ISSUE TITLE
problem with put action

### ISSUE THREAD

**Issue by seebi** [AKSW/node_ldp#7]
Error while running handler: TypeError: undefined is not a function
    at Container.create (/Users/seebi/Projects/node_ldp.git/lib/container.js:142:46)
    at /Users/seebi/Projects/node_ldp.git/lib/router.js:84:31
    at Memory.Memory.remove (/Users/seebi/Projects/node_ldp.git/lib/memory.js:63:33)
    at Container.remove (/Users/seebi/Projects/node_ldp.git/lib/container.js:170:23)
    at /Users/seebi/Projects/node_ldp.git/lib/router.js:83:27
    at Memory.Memory.exists (/Users/seebi/Projects/node_ldp.git/lib/memory.js:48:9)
    at Container.exists (/Users/seebi/Projects/node_ldp.git/lib/container.js:149:27)
    at Object.<anonymous> (/Users/seebi/Projects/node_ldp.git/lib/router.js:70:19)
    at Object.exports.Crystal.handle (/Users/seebi/Projects/node_ldp.git/lib/crystal.js:57:25)
    at Object.handle (/Users/seebi/Projects/node_ldp.git/lib/server.js:21:49)

**Comment by 0xfeedface** [comment]
`rdf get` and `rdf put` separately work for me. But `rdf edit` throws this error. There must be something that `rdf edit` does differently.
